
apiVersion: v1
kind: Service
metadata:
  name: {{ include "demo-go.fullname" . }}
  labels:
    app: demo-go
spec:
  selector:
    app: demo-go
  ports:
    - name: http
      port: {{ .Values.service.port }}
      targetPort: 8080
