
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: {{ include "demo-go.fullname" . }}
  labels:
    release: monitoring
spec:
  selector:
    matchLabels:
      app: demo-go
  endpoints:
    - port: http
      interval: 15s
      path: {{ .Values.prometheus.path }}
      relabelings: []
