
replicaCount: 1

image:
  repository: ghcr.io/chanlabs/obs-demo-go
  tag: latest
  pullPolicy: IfNotPresent

service:
  type: ClusterIP
  port: 80

resources:
  limits:
    cpu: 200m
    memory: 256Mi
  requests:
    cpu: 50m
    memory: 64Mi

otel:
  otlpEndpoint: otel-collector.monitoring.svc:4317

prometheus:
  scrape: true
  path: /metrics
  port: 8080
