{
 "title": "Demo Service Overview",
 "panels": [
  {
   "title": "Req/s",
   "type": "stat",
   "gridPos": { "x": 0, "y": 0, "w": 6, "h": 4 },
   "targets": [
    {
     "expr": "sum(rate(http_server_requests_total{service=\"demo-go-demo-go\"}[1m]))"
    }
   ]
  },
  {
   "title": "Latency P95",
   "type": "graph",
   "gridPos": { "x": 6, "y": 0, "w": 18, "h": 8 },
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum(rate(http_server_request_duration_seconds_bucket{service=\"demo-go-demo-go\"}[5m])) by (le))"
    }
   ]
  },
  {
   "title": "Error Ratio",
   "type": "graph",
   "gridPos": { "x": 0, "y": 8, "w": 12, "h": 8 },
   "targets": [
    {
     "expr": "sum(rate(http_server_requests_total{service=\"demo-go-demo-go\",status!~\"2..\"}[5m])) / sum(rate(http_server_requests_total{service=\"demo-go-demo-go\"}[5m]))"
    }
   ]
  }
 ]
}