
config:
  clients:
    - url: http://loki.monitoring.svc:3100/loki/api/v1/push
      tenant_id: "demo-go"
  snippets:
    pipelineStages:
      - cri: {}
      - json:
          expressions:
            ts: time
            level: level
            msg: msg
            trace_id: trace_id
      - labels:
          level:
      - output:
          source: msg
  positions:
    filename: /run/promtail/positions.yaml
extraScrapeConfigs: |
  - job_name: kubernetes-pods-demo
    kubernetes_sd_configs:
      - role: pod
    relabel_configs:
      - action: keep
        source_labels: [__meta_kubernetes_pod_label_app]
        regex: demo-go   # 确认和 Pod label 匹配
      - action: replace
        source_labels: [__meta_kubernetes_namespace]
        target_label: namespace
      - action: replace
        source_labels: [__meta_kubernetes_pod_name]
        target_label: pod
      - action: replace
        source_labels: [__meta_kubernetes_pod_container_name]
        target_label: container
      - action: replace
        source_labels: [__meta_kubernetes_pod_uid]
        target_label: __path__
        replacement: /var/log/pods/*$1/*.log
